//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunasMarketing.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccountView
    {
        public short Id { get; set; }
        public string Name { get; set; }
        public short BankAccountId { get; set; }
        public short BankId { get; set; }
        public string AccountNum { get; set; }
        public string Iban { get; set; }
        public string Owner { get; set; }
        public string BranchName { get; set; }
        public string BranchCode { get; set; }
        public bool HasPos { get; set; }
        public bool IsAvailable { get; set; }
    }
}
