//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunasMarketing.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequeBook
    {
        public short Id { get; set; }
        public short BankAccountId { get; set; }
        public byte LeavesCount { get; set; }
        public byte RemainingLeavesCount { get; set; }
        public string FirstLeaf { get; set; }
        public string LastLeaf { get; set; }
    }
}
