//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunasMarketing.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cheque()
        {
            this.SanadItems = new HashSet<SanadItem>();
        }
    
        public int Id { get; set; }
        public string ChequeNum { get; set; }
        public System.DateTime DueDate { get; set; }
        public decimal Amount { get; set; }
        public Nullable<short> BankAccountId { get; set; }
        public Nullable<short> BankId { get; set; }
        public string BranchName { get; set; }
        public string OwnerName { get; set; }
        public byte StatusId { get; set; }
        public string Description { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual Bank Bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanadItem> SanadItems { get; set; }
    }
}
