//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunasMarketing.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost
    {
        public short Id { get; set; }
        public string Name { get; set; }
        public short CostCategoryId { get; set; }
    
        public virtual CostCategory CostCategory { get; set; }
    }
}
