//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunasMarketing.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factor()
        {
            this.Factors1 = new HashSet<Factor>();
            this.Orders = new HashSet<Order>();
            this.FactorItems = new HashSet<FactorItem>();
        }
    
        public int Id { get; set; }
        public short PeriodId { get; set; }
        public Nullable<int> SanadId { get; set; }
        public Nullable<short> SanadPeriodId { get; set; }
        public Nullable<int> ReturnForFactorId { get; set; }
        public Nullable<short> ReturnedPeriodId { get; set; }
        public string PaperFactorCode { get; set; }
        public Nullable<short> SupplierId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal DiscountOnFactor { get; set; }
        public decimal TotalDiscount { get; set; }
        public decimal Additions { get; set; }
        public decimal Deductions { get; set; }
        public decimal TotalTax { get; set; }
        public decimal FinalPrice { get; set; }
        public int CreatorUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> MarketerId { get; set; }
        public decimal MarketerTotalCommission { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public bool IsBuy { get; set; }
        public byte FactorTypeId { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsPreFactor { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public string Description { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factor> Factors1 { get; set; }
        public virtual Factor Factor1 { get; set; }
        public virtual FiscalPeriod FiscalPeriod { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual Personnel Personnel { get; set; }
        public virtual Sanad Sanad { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FactorItem> FactorItems { get; set; }
    }
}
