//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunasMarketing.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactorItem
    {
        public int Id { get; set; }
        public int FactorId { get; set; }
        public short PeriodId { get; set; }
        public short ProductId { get; set; }
        public Nullable<double> MainUnitCount { get; set; }
        public Nullable<double> SubUnitCount { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<double> UnitsRate { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Discount { get; set; }
        public decimal Tax { get; set; }
        public decimal MarketerCommission { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal FinalPrice { get; set; }
        public string Description { get; set; }
    
        public virtual Factor Factor { get; set; }
        public virtual Product Product { get; set; }
    }
}
