//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunasMarketing.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryCheckingItem
    {
        public int Id { get; set; }
        public short InventoryCheckingId { get; set; }
        public short ProductId { get; set; }
        public double RealMainUnitCount { get; set; }
        public double SystemMainUnitCount { get; set; }
        public double Difference { get; set; }
        public bool IsCorrected { get; set; }
        public string Description { get; set; }
    
        public virtual InventoryChecking InventoryChecking { get; set; }
        public virtual Product Product { get; set; }
    }
}
