//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunasMarketing.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferItem
    {
        public int Id { get; set; }
        public short OfferId { get; set; }
        public Nullable<short> ProductId { get; set; }
        public byte OfferTypeId { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<byte> DiscountPercent { get; set; }
        public Nullable<double> MinProductCount { get; set; }
        public Nullable<short> GiftProductId { get; set; }
        public Nullable<double> GiftProductCount { get; set; }
    
        public virtual Offer Offer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
