//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunasMarketing.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> MarketerId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsVerified { get; set; }
        public Nullable<int> FactorId { get; set; }
        public Nullable<short> PeriodId { get; set; }
        public decimal TotalPrice { get; set; }
        public string Description { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Factor Factor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual Personnel Personnel { get; set; }
    }
}
