//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunasMarketing.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public short PayTypeId { get; set; }
        public int UserId { get; set; }
        public short CustomerId { get; set; }
        public System.DateTime SubmitDate { get; set; }
        public Nullable<System.DateTime> SettleDate { get; set; }
        public string IssueTracking { get; set; }
        public decimal Amount { get; set; }
        public bool IsDeposit { get; set; }
    
        public virtual PayType PayType { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual User User { get; set; }
    }
}
