//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunasMarketing.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanadItem
    {
        public int Id { get; set; }
        public int SandId { get; set; }
        public short PeriodId { get; set; }
        public Nullable<int> ChequeId { get; set; }
        public string IssueTrackingNum { get; set; }
        public short SarfaslId { get; set; }
        public Nullable<int> TafsiliId { get; set; }
        public string Description { get; set; }
        public decimal Bedeh { get; set; }
        public decimal Bestan { get; set; }
        public System.DateTime ConfirmDate { get; set; }
    
        public virtual Cheque Cheque { get; set; }
        public virtual Sanad Sanad { get; set; }
        public virtual Sarfasl Sarfasl { get; set; }
        public virtual Tafsili Tafsili { get; set; }
    }
}
