//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunasMarketing.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sarfasl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sarfasl()
        {
            this.SanadItems = new HashSet<SanadItem>();
            this.Sarfasls1 = new HashSet<Sarfasl>();
            this.Tafsilis = new HashSet<Tafsili>();
        }
    
        public short Id { get; set; }
        public Nullable<short> ParentId { get; set; }
        public string Name { get; set; }
        public byte Code { get; set; }
        public string Coding { get; set; }
        public bool IsMoeen { get; set; }
        public bool IsConstant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanadItem> SanadItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sarfasl> Sarfasls1 { get; set; }
        public virtual Sarfasl Sarfasl1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tafsili> Tafsilis { get; set; }
    }
}
