//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunasMarketing.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tafsili
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tafsili()
        {
            this.SanadItems = new HashSet<SanadItem>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> PersonnelId { get; set; }
        public Nullable<short> SupplierId { get; set; }
        public Nullable<byte> PersonTypeId { get; set; }
        public Nullable<short> ProductId { get; set; }
        public Nullable<short> BankAccId { get; set; }
        public Nullable<short> CashDeskId { get; set; }
        public Nullable<short> OtherTafsiliId { get; set; }
        public Nullable<short> SarfaslId { get; set; }
        public string MoeenName { get; set; }
        public string TafsiliName { get; set; }
        public string Coding { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual CashDesk CashDesk { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual OtherTafsili OtherTafsili { get; set; }
        public virtual Personnel Personnel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanadItem> SanadItems { get; set; }
        public virtual Sarfasl Sarfasl { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Product Product { get; set; }
    }
}
