//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunasMarketing.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.ReceiptItems = new HashSet<ReceiptItem>();
        }
    
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<short> CashDeskId { get; set; }
        public Nullable<short> BankAccountId { get; set; }
        public string IssueTracking { get; set; }
        public string Description { get; set; }
        public byte TransactionType { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual CashDesk CashDesk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptItem> ReceiptItems { get; set; }
    }
}
