//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunasMarketing.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccess
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public short ActionId { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual User User { get; set; }
    }
}
