//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunasMarketing.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Tafsili
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> PersonnelId { get; set; }
        public Nullable<short> SupplierId { get; set; }
        public Nullable<byte> PersonTypeId { get; set; }
        public Nullable<short> ProductId { get; set; }
        public Nullable<short> BankAccId { get; set; }
        public Nullable<short> CashDeskId { get; set; }
        public Nullable<short> OtherTafsiliId { get; set; }
        public Nullable<short> SarfaslId { get; set; }
        public string OwnerName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SupplierName { get; set; }
        public string ProductName { get; set; }
        public string BankName { get; set; }
        public string AccountNum { get; set; }
        public string OtName { get; set; }
        public string CashDeskName { get; set; }
    }
}
